import type { EditableLineItem } from "../types/salesInvoiceTypes";

let lineIdSeed = 0;

export const generateLineId = () => {
	lineIdSeed += 1;
	return `inv-line-${lineIdSeed}`;
};

export const createBlankLine = (): EditableLineItem => ({
	id: generateLineId(),
	itemGroup: "",
	item: "",
	itemMake: "",
	quantity: "",
	rate: "",
	uom: "",
	remarks: "",
	juteClaimAmountDtl: undefined,
	juteClaimDesc: "",
	juteClaimRate: undefined,
	juteUnitConversion: "",
	juteQtyUnitConversion: undefined,
	hessianQtyBales: undefined,
	hessianRatePerBale: undefined,
	hessianBillingRateMt: undefined,
	hessianBillingRateBale: undefined,
	govtskgPackSheet: undefined,
	govtskgNetWeight: undefined,
	govtskgTotalWeight: undefined,
});

export const buildDefaultFormValues = (skipDate = false) => ({
	branch: "",
	date: skipDate ? "" : new Date().toISOString().slice(0, 10),
	party: "",
	party_branch: "",
	delivery_order: "",
	billing_to: "",
	shipping_to: "",
	transporter: "",
	vehicle_no: "",
	eway_bill_no: "",
	eway_bill_date: "",
	challan_no: "",
	challan_date: "",
	invoice_type: "",
	footer_note: "",
	internal_note: "",
	terms_conditions: "",
	freight_charges: "",
	round_off: "",
	due_date: "",
	type_of_sale: "",
	tax_id: "",
	transporter_address: "",
	transporter_state_code: "",
	transporter_state_name: "",
	container_no: "",
	contract_no: "",
	contract_date: "",
	consignment_no: "",
	consignment_date: "",
	shipping_state_code: "",
	intra_inter_state: "",
	payment_terms: "",
	sales_order_id: "",
	sales_order_date: "",
	billing_state_code: "",
	jute_mr_no: "",
	jute_claim_amount: "",
	jute_claim_description: "",
	jute_mukam_id: "",
	govtskg_pcso_no: "",
	govtskg_pcso_date: "",
	govtskg_admin_office_address: "",
	govtskg_destination_rail_head: "",
	govtskg_loading_point: "",
	govtskg_pack_sheet: "",
	govtskg_net_weight: "",
	govtskg_total_weight: "",
});
